/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomNode: typeof import('./components/CustomNode.vue')['default']
    DragItem: typeof import('./components/DragItem.vue')['default']
  }
}
